/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Frames;

import Application.Controller;

import java.sql.SQLException;

/**
 *
 * @author LPNielsen
 */
public class BookingFrame extends javax.swing.JInternalFrame {

    private Controller con = new Controller();
    /**
     * Creates new form Booking
     */
    public BookingFrame() {
        try {
            con.viewBooking();
        }catch (SQLException e){
    }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookView3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        bookFieldRoomNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bookFieldName = new javax.swing.JTextField();
        bookFieldDateFrom = new javax.swing.JTextField();
        bookButtonSearch = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        bookFieldBooking = new javax.swing.JTextField();
        bookButtonDelete = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        bookFieldDateTo = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Booking");
        setPreferredSize(new java.awt.Dimension(1200, 779));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
                con.bookingView ,
            new String [] {
                "Booking ID", "Customer Name", "Staff Name", "Booking Date", "Check In", "Check out", "Room(s)", "Price", "Paid"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, String.class, String.class, String.class, String.class, Object.class, Double.class, Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookTable.setColumnSelectionAllowed(true);
        bookTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(bookTable);
        bookTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (bookTable.getColumnModel().getColumnCount() > 0) {
            bookTable.getColumnModel().getColumn(0).setResizable(false);
            bookTable.getColumnModel().getColumn(0).setPreferredWidth(65);
            bookTable.getColumnModel().getColumn(1).setResizable(false);
            bookTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            bookTable.getColumnModel().getColumn(2).setResizable(false);
            bookTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            bookTable.getColumnModel().getColumn(3).setResizable(false);
            bookTable.getColumnModel().getColumn(3).setPreferredWidth(75);
            bookTable.getColumnModel().getColumn(4).setResizable(false);
            bookTable.getColumnModel().getColumn(4).setPreferredWidth(60);
            bookTable.getColumnModel().getColumn(5).setResizable(false);
            bookTable.getColumnModel().getColumn(5).setPreferredWidth(60);
            bookTable.getColumnModel().getColumn(6).setResizable(false);
            bookTable.getColumnModel().getColumn(7).setResizable(false);
            bookTable.getColumnModel().getColumn(8).setResizable(false);
            bookTable.getColumnModel().getColumn(8).setPreferredWidth(35);
        }

        bookFieldRoomNo.setText("Room no.");
        bookFieldRoomNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookFieldRoomNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookFieldRoomNoFocusLost(evt);
            }
        });

        jLabel19.setText("Booking ID:");

        jLabel20.setText("Name: ");

        jLabel21.setText("Date From:");

        bookFieldName.setText("Name");
        bookFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookFieldNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookFieldNameFocusLost(evt);
            }
        });

        bookFieldDateFrom.setText("yyyy-mm-dd");
        bookFieldDateFrom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookFieldDateFromFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookFieldDateFromFocusLost(evt);
            }
        });

        bookButtonSearch.setText("Search");
        bookButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonSearchActionPerformed(evt);
            }
        });

        jLabel22.setText("Booking ID:");

        bookFieldBooking.setText("Booking ID");
        bookFieldBooking.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookFieldBookingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookFieldBookingFocusLost(evt);
            }
        });

        bookButtonDelete.setText("Delete");
        bookButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonDeleteActionPerformed(evt);
            }
        });

        jLabel24.setText("Date To:");

        bookFieldDateTo.setText("yyyy-mm-dd");
        bookFieldDateTo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookFieldDateToFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookFieldDateToFocusLost(evt);
            }
        });
        bookFieldDateTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFieldDateToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookView3Layout = new javax.swing.GroupLayout(bookView3);
        bookView3.setLayout(bookView3Layout);
        bookView3Layout.setHorizontalGroup(
            bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookView3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bookView3Layout.createSequentialGroup()
                        .addGroup(bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24))
                        .addGap(34, 34, 34)
                        .addGroup(bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bookFieldRoomNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookFieldDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(bookButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookFieldDateTo, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bookView3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(34, 34, 34)
                        .addGroup(bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookFieldBooking)
                            .addComponent(bookButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE))
        );
        bookView3Layout.setVerticalGroup(
            bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(bookView3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookFieldRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(bookFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(bookFieldDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(bookFieldDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bookButtonSearch)
                .addGap(130, 130, 130)
                .addGroup(bookView3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(bookFieldBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bookButtonDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookView3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bookView3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookFieldDateToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFieldDateToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookFieldDateToActionPerformed

    private void bookFieldDateToFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldDateToFocusLost
        if (bookFieldDateTo.getText().equals("")){
            bookFieldDateTo.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_bookFieldDateToFocusLost

    private void bookFieldDateToFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldDateToFocusGained
        if (bookFieldDateTo.getText().equals("yyyy-mm-dd")){
            bookFieldDateTo.setText("");
        }
    }//GEN-LAST:event_bookFieldDateToFocusGained

    private void bookFieldBookingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldBookingFocusLost
        if (bookFieldBooking.getText().equals("")){
            bookFieldBooking.setText("Booking ID");
        }
    }//GEN-LAST:event_bookFieldBookingFocusLost

    private void bookFieldBookingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldBookingFocusGained
        if (bookFieldBooking.getText().equals("Booking ID")){
            bookFieldBooking.setText("");
        }
    }//GEN-LAST:event_bookFieldBookingFocusGained

    private void bookFieldDateFromFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldDateFromFocusLost
        if (bookFieldDateFrom.getText().equals("")){
            bookFieldDateFrom.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_bookFieldDateFromFocusLost

    private void bookFieldDateFromFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldDateFromFocusGained
        if (bookFieldDateFrom.getText().equals("yyyy-mm-dd")){
            bookFieldDateFrom.setText("");
        }
    }//GEN-LAST:event_bookFieldDateFromFocusGained

    private void bookFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldNameFocusLost
        if (bookFieldName.getText().equals("")){
            bookFieldName.setText("Name");
        }
    }//GEN-LAST:event_bookFieldNameFocusLost

    private void bookFieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldNameFocusGained
        // TODO add your handling code here:
        if (bookFieldName.getText().equals("Name")){
            bookFieldName.setText("");
        }
    }//GEN-LAST:event_bookFieldNameFocusGained

    private void bookFieldRoomNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldRoomNoFocusLost
        // TODO add your handling code here:
        if (bookFieldRoomNo.getText().equals("")){
            bookFieldRoomNo.setText("Room no.");
        }
    }//GEN-LAST:event_bookFieldRoomNoFocusLost

    private void bookFieldRoomNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookFieldRoomNoFocusGained
        // TODO add your handling code here:
        if (bookFieldRoomNo.getText().equals("Room no.")){
            bookFieldRoomNo.setText("");
        }
    }//GEN-LAST:event_bookFieldRoomNoFocusGained

    private void bookButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookButtonDeleteActionPerformed

    private void bookButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookButtonSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookButtonDelete;
    private javax.swing.JButton bookButtonSearch;
    private javax.swing.JTextField bookFieldBooking;
    private javax.swing.JTextField bookFieldDateFrom;
    private javax.swing.JTextField bookFieldDateTo;
    private javax.swing.JTextField bookFieldName;
    private javax.swing.JTextField bookFieldRoomNo;
    private javax.swing.JTable bookTable;
    private javax.swing.JPanel bookView3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
