/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Frames;

/**
 *
 * @author LPNielsen
 */
public class CateringFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Catering
     */
    public CateringFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catView = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        catTable = new javax.swing.JTable();
        catFieldCatID1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        catFieldName = new javax.swing.JTextField();
        catButtonSearch = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        catFieldCatID2 = new javax.swing.JTextField();
        catButtonDelete = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        catFieldDate = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Catering");
        setPreferredSize(new java.awt.Dimension(1200, 779));

        catTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Catering ID", "Customer Name", "Staff Name", "Order Date", "Event Date", "Time", "Price", "Paid"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, String.class, String.class, String.class, String.class, Double.class, Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catTable.setColumnSelectionAllowed(true);
        catTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(catTable);
        catTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        catFieldCatID1.setText("Catering ID");
        catFieldCatID1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                catFieldCatID1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                catFieldCatID1FocusLost(evt);
            }
        });

        jLabel19.setText("Catering ID:");

        jLabel20.setText("Name: ");

        catFieldName.setText("Name");
        catFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                catFieldNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                catFieldNameFocusLost(evt);
            }
        });

        catButtonSearch.setText("Search");
        catButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catButtonSearchjButton1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Catering ID");

        catFieldCatID2.setText("Catering ID");
        catFieldCatID2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                catFieldCatID2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                catFieldCatID2FocusLost(evt);
            }
        });

        catButtonDelete.setText("Delete");
        catButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catButtonDeleteActionPerformed(evt);
            }
        });

        jLabel24.setText("Date:");

        catFieldDate.setText("Date");
        catFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                catFieldDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                catFieldDateFocusLost(evt);
            }
        });

        javax.swing.GroupLayout catViewLayout = new javax.swing.GroupLayout(catView);
        catView.setLayout(catViewLayout);
        catViewLayout.setHorizontalGroup(
            catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(catViewLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(34, 34, 34)
                        .addGroup(catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(catFieldCatID2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(catButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                    .addGroup(catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(catViewLayout.createSequentialGroup()
                            .addGroup(catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel24))
                            .addGap(30, 30, 30)
                            .addGroup(catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(catFieldDate)
                                .addComponent(catFieldCatID1)
                                .addComponent(catFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(catButtonSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        catViewLayout.setVerticalGroup(
            catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catViewLayout.createSequentialGroup()
                .addGroup(catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catFieldCatID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(catFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(catFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(catButtonSearch)
                .addGap(116, 116, 116)
                .addGroup(catViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(catFieldCatID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(catButtonDelete)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(catViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catFieldCatID1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catFieldCatID1FocusGained
        // TODO add your handling code here:
        if (catFieldCatID1.getText().equals("Catering ID")){
            catFieldCatID1.setText("");
        }
    }//GEN-LAST:event_catFieldCatID1FocusGained

    private void catFieldCatID1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catFieldCatID1FocusLost
        // TODO add your handling code here:
        if (catFieldCatID1.getText().equals("")){
            catFieldCatID1.setText("Catering ID");
        }
    }//GEN-LAST:event_catFieldCatID1FocusLost

    private void catFieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catFieldNameFocusGained
        // TODO add your handling code here:
        if (catFieldName.getText().equals("Name")){
            catFieldName.setText("");
        }
    }//GEN-LAST:event_catFieldNameFocusGained

    private void catFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catFieldNameFocusLost
        if (catFieldName.getText().equals("")){
            catFieldName.setText("Name");
        }
    }//GEN-LAST:event_catFieldNameFocusLost

    private void catButtonSearchjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catButtonSearchjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catButtonSearchjButton1ActionPerformed

    private void catFieldCatID2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catFieldCatID2FocusGained
        if (catFieldCatID2.getText().equals("Catering ID")){
            catFieldCatID2.setText("");
        }
    }//GEN-LAST:event_catFieldCatID2FocusGained

    private void catFieldCatID2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catFieldCatID2FocusLost
        if (catFieldCatID2.getText().equals("")){
            catFieldCatID2.setText("Catering ID");
        }
    }//GEN-LAST:event_catFieldCatID2FocusLost

    private void catFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catFieldDateFocusGained
        // TODO add your handling code here:
        if (catFieldDate.getText().equals("yyyy-mm-dd")){
            catFieldDate.setText("");
        }
    }//GEN-LAST:event_catFieldDateFocusGained

    private void catFieldDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catFieldDateFocusLost
        // TODO add your handling code here:
        if (catFieldDate.getText().equals("")){
            catFieldDate.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_catFieldDateFocusLost

    private void catButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catButtonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton catButtonDelete;
    private javax.swing.JButton catButtonSearch;
    private javax.swing.JTextField catFieldCatID1;
    private javax.swing.JTextField catFieldCatID2;
    private javax.swing.JTextField catFieldDate;
    private javax.swing.JTextField catFieldName;
    private javax.swing.JTable catTable;
    private javax.swing.JPanel catView;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
