/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Frames;

import Application.Controller;

import java.awt.CardLayout;

/**
 *
 * @author LPNielsen
 */
public class CreateFrame extends javax.swing.JInternalFrame {
    private CardLayout cl;
    private Controller controller;
    /**
     * Creates new form CreateFrame
     */
    public CreateFrame(Controller con) {
        initComponents();
        controller = con;
        cl = new CardLayout();
        controller = con;
        creCPanelEvent.setLayout(cl);
        creCPanelEvent.add("crePanelArr",crePanelArr);
        creCPanelEvent.add("crePanelBook",crePanelBook);
        creCPanelEvent.add("crePanelCat",crePanelCat);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        creCPanelEvent = new javax.swing.JPanel();
        crePanelArr = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        creCBoxArr = new javax.swing.JComboBox<>();
        creFieldArrDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        creTableArr = new javax.swing.JTable();
        creButtonArrCreate = new javax.swing.JButton();
        creButtonArrSearch = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        creTAreaArrComment = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        crePanelBook = new javax.swing.JPanel();
        creCBoxBook = new javax.swing.JComboBox<>();
        creFieldBookDateFrom = new javax.swing.JTextField();
        creFieldBookDateTo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        creTableBook = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        creTAreaBookComment = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        creButtonBookSearch = new javax.swing.JButton();
        creButtonBookCreate = new javax.swing.JButton();
        crePanelCat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        creFieldCatAddress = new javax.swing.JTextField();
        creFieldCatDate = new javax.swing.JTextField();
        creFieldCatZIP = new javax.swing.JTextField();
        creFieldCatAmount = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        creTableCat = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        creTAreaCatComment = new javax.swing.JTextArea();
        creJBoxCatTime = new javax.swing.JComboBox<>();
        creButtonCatCreate = new javax.swing.JButton();
        crePanelCustomer = new javax.swing.JPanel();
        creFieldAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        creFieldEmail = new javax.swing.JTextField();
        creFieldPhoneNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        creFieldLName = new javax.swing.JTextField();
        creFieldFName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        creFieldZIP = new javax.swing.JTextField();
        creFieldCusID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        creRButtonArr = new javax.swing.JRadioButton();
        creRButtonBook = new javax.swing.JRadioButton();
        creRButtonCat = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Create");
        setPreferredSize(new java.awt.Dimension(1200, 779));

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 779));

        creCPanelEvent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        creCPanelEvent.setPreferredSize(new java.awt.Dimension(700, 380));
        creCPanelEvent.setLayout(new CardLayout());

        crePanelArr.setPreferredSize(new java.awt.Dimension(704, 300));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Arrangement");

        jLabel15.setText("Event Type:");

        jLabel16.setText("Date:");

        creCBoxArr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Birthday", "Party", "Conference", " " }));

        creFieldArrDate.setText("yyyy-mm-dd");
        creFieldArrDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldArrDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldArrDateFocusLost(evt);
            }
        });

        creTableArr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room No", "Room Type", "Description", "Price", "Select"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, Double.class, Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(creTableArr);
        if (creTableArr.getColumnModel().getColumnCount() > 0) {
            creTableArr.getColumnModel().getColumn(0).setResizable(false);
            creTableArr.getColumnModel().getColumn(0).setPreferredWidth(20);
            creTableArr.getColumnModel().getColumn(1).setResizable(false);
            creTableArr.getColumnModel().getColumn(1).setPreferredWidth(20);
            creTableArr.getColumnModel().getColumn(2).setResizable(false);
            creTableArr.getColumnModel().getColumn(2).setPreferredWidth(200);
            creTableArr.getColumnModel().getColumn(3).setResizable(false);
            creTableArr.getColumnModel().getColumn(3).setPreferredWidth(50);
            creTableArr.getColumnModel().getColumn(4).setResizable(false);
            creTableArr.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        creButtonArrCreate.setText("Create");
        creButtonArrCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creButtonArrCreateActionPerformed(evt);
            }
        });

        creButtonArrSearch.setText("Search");
        creButtonArrSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creButtonArrSearchActionPerformed(evt);
            }
        });

        creTAreaArrComment.setColumns(20);
        creTAreaArrComment.setRows(5);
        jScrollPane6.setViewportView(creTAreaArrComment);

        jLabel24.setText("Comment:");

        javax.swing.GroupLayout crePanelArrLayout = new javax.swing.GroupLayout(crePanelArr);
        crePanelArr.setLayout(crePanelArrLayout);
        crePanelArrLayout.setHorizontalGroup(
            crePanelArrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelArrLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(crePanelArrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelArrLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creFieldArrDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creButtonArrSearch)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelArrLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(crePanelArrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(creCBoxArr, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(218, 218, 218))))
            .addGroup(crePanelArrLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(crePanelArrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(crePanelArrLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(creButtonArrCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        crePanelArrLayout.setVerticalGroup(
            crePanelArrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crePanelArrLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crePanelArrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creCBoxArr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(crePanelArrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(creFieldArrDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creButtonArrSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crePanelArrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creButtonArrCreate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelArrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(crePanelArrLayout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel24))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        creCPanelEvent.add(crePanelArr, "card2");

        creCBoxBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Honeymoon", "Ocean View" }));

        creFieldBookDateFrom.setText("yyyy-mm-dd");
        creFieldBookDateFrom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldBookDateFromFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldBookDateFromFocusLost(evt);
            }
        });

        creFieldBookDateTo.setText("yyyy-mm-dd");
        creFieldBookDateTo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldBookDateToFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldBookDateToFocusLost(evt);
            }
        });

        creTableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room No", "Room Type", "Description", "Price", "Select"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, Double.class, Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(creTableBook);
        if (creTableBook.getColumnModel().getColumnCount() > 0) {
            creTableBook.getColumnModel().getColumn(0).setResizable(false);
            creTableBook.getColumnModel().getColumn(0).setPreferredWidth(20);
            creTableBook.getColumnModel().getColumn(1).setResizable(false);
            creTableBook.getColumnModel().getColumn(1).setPreferredWidth(20);
            creTableBook.getColumnModel().getColumn(2).setResizable(false);
            creTableBook.getColumnModel().getColumn(2).setPreferredWidth(200);
            creTableBook.getColumnModel().getColumn(3).setResizable(false);
            creTableBook.getColumnModel().getColumn(3).setPreferredWidth(50);
            creTableBook.getColumnModel().getColumn(4).setResizable(false);
            creTableBook.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        creTAreaBookComment.setColumns(20);
        creTAreaBookComment.setRows(5);
        jScrollPane5.setViewportView(creTAreaBookComment);

        jLabel6.setText("Room Type:");

        jLabel7.setText("From Date:");

        jLabel8.setText("To Date:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Booking");

        jLabel22.setText("Comment:");

        creButtonBookSearch.setText("Search");
        creButtonBookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creButtonBookSearchActionPerformed(evt);
            }
        });

        creButtonBookCreate.setText("Create");
        creButtonBookCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creButtonBookCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crePanelBookLayout = new javax.swing.GroupLayout(crePanelBook);
        crePanelBook.setLayout(crePanelBookLayout);
        crePanelBookLayout.setHorizontalGroup(
            crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crePanelBookLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelBookLayout.createSequentialGroup()
                        .addGroup(crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creFieldBookDateTo)
                            .addComponent(creFieldBookDateFrom)
                            .addComponent(creCBoxBook, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creButtonBookSearch)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelBookLayout.createSequentialGroup()
                        .addGroup(crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(crePanelBookLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(creButtonBookCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelBookLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(318, 318, 318))))
        );
        crePanelBookLayout.setVerticalGroup(
            crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelBookLayout.createSequentialGroup()
                .addGroup(crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(crePanelBookLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(creButtonBookCreate))
                    .addGroup(crePanelBookLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(7, 7, 7)
                        .addGroup(crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creCBoxBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creFieldBookDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creFieldBookDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(creButtonBookSearch))
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addGroup(crePanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crePanelBookLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelBookLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        creCPanelEvent.add(crePanelBook, "card3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Catering");

        jLabel3.setText("Address:");

        jLabel18.setText("ZIP:");

        jLabel19.setText("Time:");

        jLabel20.setText("Date:");

        jLabel21.setText("Comment:");

        jLabel23.setText("People Count:");

        creFieldCatAddress.setText("Address");
        creFieldCatAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldCatAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldCatAddressFocusLost(evt);
            }
        });

        creFieldCatDate.setText("yyyy-mm-dd");
        creFieldCatDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldCatDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldCatDateFocusLost(evt);
            }
        });

        creFieldCatZIP.setText("ZIP");
        creFieldCatZIP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldCatZIPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldCatZIPFocusLost(evt);
            }
        });

        creFieldCatAmount.setText("Amount");
        creFieldCatAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldCatAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldCatAmountFocusLost(evt);
            }
        });

        creTableCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Description", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, Double.class, Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(creTableCat);
        if (creTableCat.getColumnModel().getColumnCount() > 0) {
            creTableCat.getColumnModel().getColumn(0).setResizable(false);
            creTableCat.getColumnModel().getColumn(0).setPreferredWidth(20);
            creTableCat.getColumnModel().getColumn(1).setResizable(false);
            creTableCat.getColumnModel().getColumn(1).setPreferredWidth(250);
            creTableCat.getColumnModel().getColumn(2).setPreferredWidth(30);
            creTableCat.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        creTAreaCatComment.setColumns(20);
        creTAreaCatComment.setRows(5);
        creTAreaCatComment.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        creTAreaCatComment.setPreferredSize(new java.awt.Dimension(164, 61));
        jScrollPane4.setViewportView(creTAreaCatComment);

        creJBoxCatTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30", "21:45", "22:00" }));

        creButtonCatCreate.setText("Create");
        creButtonCatCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creButtonCatCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crePanelCatLayout = new javax.swing.GroupLayout(crePanelCat);
        crePanelCat.setLayout(crePanelCatLayout);
        crePanelCatLayout.setHorizontalGroup(
            crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crePanelCatLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel3)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(creFieldCatAddress)
                    .addComponent(creJBoxCatTime, 0, 170, Short.MAX_VALUE)
                    .addComponent(creFieldCatAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creFieldCatZIP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creFieldCatDate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelCatLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelCatLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(317, 317, 317))
                    .addGroup(crePanelCatLayout.createSequentialGroup()
                        .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(crePanelCatLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4)
                                .addGap(18, 18, 18)
                                .addComponent(creButtonCatCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );
        crePanelCatLayout.setVerticalGroup(
            crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crePanelCatLayout.createSequentialGroup()
                .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crePanelCatLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creFieldCatDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creFieldCatZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(crePanelCatLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creFieldCatAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(creJBoxCatTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creFieldCatAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crePanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(creButtonCatCreate)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        creCPanelEvent.add(crePanelCat, "card4");

        crePanelCustomer.setPreferredSize(new java.awt.Dimension(273, 230));

        creFieldAddress.setText("Address");
        creFieldAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldAddressFocusLost(evt);
            }
        });

        jLabel12.setText("Street");

        jLabel11.setText("Email Add:");

        creFieldEmail.setText("Email");
        creFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldEmailFocusLost(evt);
            }
        });

        creFieldPhoneNo.setText("Phone No");
        creFieldPhoneNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldPhoneNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldPhoneNoFocusLost(evt);
            }
        });
        creFieldPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creFieldPhoneNoActionPerformed(evt);
            }
        });

        jLabel10.setText("Phone No:");

        jLabel9.setText("Last Name:");

        creFieldLName.setText("Last Name");
        creFieldLName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldLNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldLNameFocusLost(evt);
            }
        });

        creFieldFName.setText("First Name");
        creFieldFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldFNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldFNameFocusLost(evt);
            }
        });

        jLabel5.setText("First Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Create Customer");

        jLabel14.setText("ZIP:");

        creFieldZIP.setText("ZIP");
        creFieldZIP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldZIPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldZIPFocusLost(evt);
            }
        });

        javax.swing.GroupLayout crePanelCustomerLayout = new javax.swing.GroupLayout(crePanelCustomer);
        crePanelCustomer.setLayout(crePanelCustomerLayout);
        crePanelCustomerLayout.setHorizontalGroup(
            crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crePanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(creFieldEmail)
                    .addComponent(creFieldAddress)
                    .addComponent(creFieldZIP)
                    .addComponent(creFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creFieldLName)
                    .addComponent(creFieldPhoneNo))
                .addGap(12, 12, 12))
        );
        crePanelCustomerLayout.setVerticalGroup(
            crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crePanelCustomerLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(creFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creFieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(creFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crePanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creFieldZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        creFieldCusID.setText("Customer ID");
        creFieldCusID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                creFieldCusIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                creFieldCusIDFocusLost(evt);
            }
        });

        jLabel1.setText("Existing Customer:");

        buttonGroup1.add(creRButtonArr);
        creRButtonArr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        creRButtonArr.setText("Arrangement");
        creRButtonArr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creRButtonArrActionPerformed(evt);
            }
        });

        buttonGroup1.add(creRButtonBook);
        creRButtonBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        creRButtonBook.setText("Booking");
        creRButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creRButtonBookActionPerformed(evt);
            }
        });

        buttonGroup1.add(creRButtonCat);
        creRButtonCat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        creRButtonCat.setText("Catering");
        creRButtonCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creRButtonCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creFieldCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(creRButtonArr)
                        .addGap(18, 18, 18)
                        .addComponent(creRButtonBook)
                        .addGap(18, 18, 18)
                        .addComponent(creRButtonCat)))
                .addGap(13, 474, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(creCPanelEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(crePanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(455, 455, 455))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creRButtonArr)
                    .addComponent(creRButtonBook)
                    .addComponent(creRButtonCat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(creFieldCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crePanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creCPanelEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creRButtonArrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creRButtonArrActionPerformed
        // TODO add your handling code here:
        cl.show(creCPanelEvent,"crePanelArr");
    }//GEN-LAST:event_creRButtonArrActionPerformed

    private void creRButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creRButtonBookActionPerformed
        // TODO add your handling code here:
        cl.show(creCPanelEvent,"crePanelBook");
    }//GEN-LAST:event_creRButtonBookActionPerformed

    private void creRButtonCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creRButtonCatActionPerformed
        // TODO add your handling code here:
        cl.show(creCPanelEvent,"crePanelCat");
    }//GEN-LAST:event_creRButtonCatActionPerformed

    private void creFieldPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creFieldPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creFieldPhoneNoActionPerformed

    private void creFieldCusIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCusIDFocusGained
        // TODO add your handling code here:
        if (creFieldCusID.getText().equals("Customer ID")) {
            creFieldCusID.setText("");
        }
    }//GEN-LAST:event_creFieldCusIDFocusGained

    private void creFieldCusIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCusIDFocusLost
        // TODO add your handling code here:
        if (creFieldCusID.getText().equals("")) {
            creFieldCusID.setText("Customer ID");
        }
    }//GEN-LAST:event_creFieldCusIDFocusLost

    private void creFieldFNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldFNameFocusGained
        // TODO add your handling code here:
        if (creFieldFName.getText().equals("First Name")) {
            creFieldFName.setText("");
        }
    }//GEN-LAST:event_creFieldFNameFocusGained

    private void creFieldFNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldFNameFocusLost
        // TODO add your handling code here:
        if (creFieldFName.getText().equals("")) {
            creFieldFName.setText("First Name");
        }
    }//GEN-LAST:event_creFieldFNameFocusLost

    private void creFieldLNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldLNameFocusGained
        // TODO add your handling code here:
        if (creFieldLName.getText().equals("Last Name")) {
            creFieldLName.setText("");
        }
    }//GEN-LAST:event_creFieldLNameFocusGained

    private void creFieldLNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldLNameFocusLost
        // TODO add your handling code here:
        if (creFieldLName.getText().equals("")) {
            creFieldLName.setText("Last Name");
        }
    }//GEN-LAST:event_creFieldLNameFocusLost

    private void creFieldPhoneNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldPhoneNoFocusGained
        // TODO add your handling code here:
        if (creFieldPhoneNo.getText().equals("Phone No")) {
            creFieldPhoneNo.setText("");
        }
    }//GEN-LAST:event_creFieldPhoneNoFocusGained

    private void creFieldPhoneNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldPhoneNoFocusLost
        // TODO add your handling code here:
        if (creFieldPhoneNo.getText().equals("")) {
            creFieldPhoneNo.setText("Phone No");
        }
    }//GEN-LAST:event_creFieldPhoneNoFocusLost

    private void creFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldEmailFocusGained
        // TODO add your handling code here:
        if (creFieldEmail.getText().equals("Email")) {
            creFieldEmail.setText("");
        }
    }//GEN-LAST:event_creFieldEmailFocusGained

    private void creFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldEmailFocusLost
        // TODO add your handling code here:
        if (creFieldEmail.getText().equals("")) {
            creFieldEmail.setText("Email");
        }
    }//GEN-LAST:event_creFieldEmailFocusLost

    private void creFieldAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldAddressFocusGained
        // TODO add your handling code here:
        if (creFieldAddress.getText().equals("Address")) {
            creFieldAddress.setText("");
        }
    }//GEN-LAST:event_creFieldAddressFocusGained

    private void creFieldAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldAddressFocusLost
        // TODO add your handling code here:
        if (creFieldAddress.getText().equals("")) {
            creFieldAddress.setText("Address");
        }
    }//GEN-LAST:event_creFieldAddressFocusLost

    private void creFieldZIPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldZIPFocusGained
        // TODO add your handling code here:
        if (creFieldZIP.getText().equals("ZIP")) {
            creFieldZIP.setText("");
        }
    }//GEN-LAST:event_creFieldZIPFocusGained

    private void creFieldZIPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldZIPFocusLost
        // TODO add your handling code here:
        if (creFieldZIP.getText().equals("")) {
            creFieldZIP.setText("ZIP");
        }
    }//GEN-LAST:event_creFieldZIPFocusLost

    private void creFieldArrDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldArrDateFocusGained
        // TODO add your handling code here:
        if (creFieldArrDate.getText().equals("yyyy-mm-dd")) {
            creFieldArrDate.setText("");
        }
    }//GEN-LAST:event_creFieldArrDateFocusGained

    private void creFieldArrDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldArrDateFocusLost
        // TODO add your handling code here:
        if (creFieldArrDate.getText().equals("")) {
            creFieldArrDate.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_creFieldArrDateFocusLost

    private void creFieldBookDateFromFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldBookDateFromFocusGained
        // TODO add your handling code here:
        if (creFieldBookDateFrom.getText().equals("yyyy-mm-dd")) {
            creFieldBookDateFrom.setText("");
        }
    }//GEN-LAST:event_creFieldBookDateFromFocusGained

    private void creFieldBookDateFromFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldBookDateFromFocusLost
        // TODO add your handling code here:
        if (creFieldBookDateFrom.getText().equals("")) {
            creFieldBookDateFrom.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_creFieldBookDateFromFocusLost

    private void creFieldBookDateToFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldBookDateToFocusGained
        // TODO add your handling code here:
        if (creFieldBookDateTo.getText().equals("yyyy-mm-dd")) {
            creFieldBookDateTo.setText("");
        }
    }//GEN-LAST:event_creFieldBookDateToFocusGained

    private void creFieldBookDateToFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldBookDateToFocusLost
        // TODO add your handling code here:
        if (creFieldBookDateTo.getText().equals("")) {
            creFieldBookDateTo.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_creFieldBookDateToFocusLost

    private void creFieldCatAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCatAddressFocusGained
        // TODO add your handling code here:
        if (creFieldCatAddress.getText().equals("Address")) {
            creFieldCatAddress.setText("");
        }
    }//GEN-LAST:event_creFieldCatAddressFocusGained

    private void creFieldCatAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCatAddressFocusLost
        // TODO add your handling code here:
        if (creFieldCatAddress.getText().equals("")) {
            creFieldCatAddress.setText("Address");
        }
    }//GEN-LAST:event_creFieldCatAddressFocusLost

    private void creFieldCatDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCatDateFocusGained
        // TODO add your handling code here:
        if (creFieldCatDate.getText().equals("yyyy-mm-dd")) {
            creFieldCatDate.setText("");
        }
    }//GEN-LAST:event_creFieldCatDateFocusGained

    private void creFieldCatDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCatDateFocusLost
        // TODO add your handling code here:
        if (creFieldCatDate.getText().equals("")) {
            creFieldCatDate.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_creFieldCatDateFocusLost

    private void creFieldCatZIPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCatZIPFocusGained
        // TODO add your handling code here:
        if (creFieldCatZIP.getText().equals("ZIP")) {
            creFieldCatZIP.setText("");
        }
    }//GEN-LAST:event_creFieldCatZIPFocusGained

    private void creFieldCatZIPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCatZIPFocusLost
        // TODO add your handling code here:
        if (creFieldCatZIP.getText().equals("")) {
            creFieldCatZIP.setText("ZIP");
        }
    }//GEN-LAST:event_creFieldCatZIPFocusLost

    private void creFieldCatAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCatAmountFocusGained
        // TODO add your handling code here:
        if (creFieldCatAmount.getText().equals("Amount")) {
            creFieldCatAmount.setText("");
        }
    }//GEN-LAST:event_creFieldCatAmountFocusGained

    private void creFieldCatAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_creFieldCatAmountFocusLost
        // TODO add your handling code here:
        if (creFieldCatAmount.getText().equals("")) {
            creFieldCatAmount.setText("Amount");
        }
    }//GEN-LAST:event_creFieldCatAmountFocusLost

    private void creButtonArrSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creButtonArrSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creButtonArrSearchActionPerformed

    private void creButtonArrCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creButtonArrCreateActionPerformed




    }//GEN-LAST:event_creButtonArrCreateActionPerformed

    private void creButtonBookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creButtonBookSearchActionPerformed



    }//GEN-LAST:event_creButtonBookSearchActionPerformed

    private void creButtonBookCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creButtonBookCreateActionPerformed
        if(creFieldCusID.getText().equalsIgnoreCase("customer id")){
            controller.
        }

    }//GEN-LAST:event_creButtonBookCreateActionPerformed

    private void creButtonCatCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creButtonCatCreateActionPerformed

    }//GEN-LAST:event_creButtonCatCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton creButtonArrCreate;
    private javax.swing.JButton creButtonArrSearch;
    private javax.swing.JButton creButtonBookCreate;
    private javax.swing.JButton creButtonBookSearch;
    private javax.swing.JButton creButtonCatCreate;
    private javax.swing.JComboBox<String> creCBoxArr;
    private javax.swing.JComboBox<String> creCBoxBook;
    private javax.swing.JPanel creCPanelEvent;
    private javax.swing.JTextField creFieldAddress;
    private javax.swing.JTextField creFieldArrDate;
    private javax.swing.JTextField creFieldBookDateFrom;
    private javax.swing.JTextField creFieldBookDateTo;
    private javax.swing.JTextField creFieldCatAddress;
    private javax.swing.JTextField creFieldCatAmount;
    private javax.swing.JTextField creFieldCatDate;
    private javax.swing.JTextField creFieldCatZIP;
    private javax.swing.JTextField creFieldCusID;
    private javax.swing.JTextField creFieldEmail;
    private javax.swing.JTextField creFieldFName;
    private javax.swing.JTextField creFieldLName;
    private javax.swing.JTextField creFieldPhoneNo;
    private javax.swing.JTextField creFieldZIP;
    private javax.swing.JComboBox<String> creJBoxCatTime;
    private javax.swing.JPanel crePanelArr;
    private javax.swing.JPanel crePanelBook;
    private javax.swing.JPanel crePanelCat;
    private javax.swing.JPanel crePanelCustomer;
    private javax.swing.JRadioButton creRButtonArr;
    private javax.swing.JRadioButton creRButtonBook;
    private javax.swing.JRadioButton creRButtonCat;
    private javax.swing.JTextArea creTAreaArrComment;
    private javax.swing.JTextArea creTAreaBookComment;
    private javax.swing.JTextArea creTAreaCatComment;
    private javax.swing.JTable creTableArr;
    private javax.swing.JTable creTableBook;
    private javax.swing.JTable creTableCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
