/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Frames;

import Application.Controller;

import java.sql.SQLException;

/**
 *
 * @author LPNielsen
 */
public class EmployeeFrame extends javax.swing.JInternalFrame {
    private Controller con;
    /**
     * Creates new form Frame1
     */
    public EmployeeFrame() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empView = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        empFieldEmpID = new javax.swing.JTextField();
        empFieldName = new javax.swing.JTextField();
        empFieldDate = new javax.swing.JTextField();
        empFieldEmpIDDelete = new javax.swing.JTextField();
        empFieldCreateAddress = new javax.swing.JTextField();
        empFieldCreateEmail = new javax.swing.JTextField();
        empFieldCreatePhoneNo = new javax.swing.JTextField();
        empFieldCreateLName = new javax.swing.JTextField();
        empFieldCreateFName = new javax.swing.JTextField();
        empFieldCreateZIP = new javax.swing.JTextField();
        empButtonSearch = new javax.swing.JButton();
        empButtonDelete = new javax.swing.JButton();
        empButtonCreate = new javax.swing.JButton();
        empCBoxLevel = new javax.swing.JComboBox<>();
        empCBOXTitle = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Employee");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(1200, 779));

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Email", "Phone No", "Address", "ZIP", "Start Date", "User Name", "User Level"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, String.class, String.class, String.class, Integer.class, String.class, String.class, Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empTable.setColumnSelectionAllowed(true);
        empTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(empTable);
        empTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        empFieldEmpID.setText("Employee ID");
        empFieldEmpID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldEmpIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldEmpIDFocusLost(evt);
            }
        });

        empFieldName.setText("Name");
        empFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldNameFocusLost(evt);
            }
        });

        empFieldDate.setText("yyyy-mm-dd");
        empFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldDateFocusLost(evt);
            }
        });

        empFieldEmpIDDelete.setText("Employee ID");
        empFieldEmpIDDelete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldEmpIDDeleteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldEmpIDDeleteFocusLost(evt);
            }
        });

        empFieldCreateAddress.setText("Address");
        empFieldCreateAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldCreateAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldCreateAddressFocusLost(evt);
            }
        });

        empFieldCreateEmail.setText("Email");
        empFieldCreateEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldCreateEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldCreateEmailFocusLost(evt);
            }
        });

        empFieldCreatePhoneNo.setText("Phone No");
        empFieldCreatePhoneNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldCreatePhoneNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldCreatePhoneNoFocusLost(evt);
            }
        });
        empFieldCreatePhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empFieldCreatePhoneNoActionPerformed(evt);
            }
        });

        empFieldCreateLName.setText("Last Name");
        empFieldCreateLName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldCreateLNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldCreateLNameFocusLost(evt);
            }
        });

        empFieldCreateFName.setText("First Name");
        empFieldCreateFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldCreateFNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldCreateFNameFocusLost(evt);
            }
        });

        empFieldCreateZIP.setText("ZIP");
        empFieldCreateZIP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFieldCreateZIPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empFieldCreateZIPFocusLost(evt);
            }
        });

        empButtonSearch.setText("Search");
        empButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empButtonSearchjButton1ActionPerformed(evt);
            }
        });

        empButtonDelete.setText("Delete");
        empButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empButtonDeleteActionPerformed(evt);
            }
        });

        empButtonCreate.setText("Create");
        empButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    empButtonCreateActionPerformed(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        empCBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Employee" }));

        empCBOXTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receptionist", "Cook", "Administrator", " " }));

        jLabel21.setText("Employee ID:");

        jLabel24.setText("Name: ");

        jLabel25.setText("Employee ID:");

        jLabel22.setText("Date:");

        jLabel12.setText("Street");

        jLabel11.setText("Email Add:");

        jLabel10.setText("Phone No:");

        jLabel9.setText("Last Name:");

        jLabel5.setText("First Name:");

        jLabel14.setText("ZIP:");

        jLabel1.setText("User Level:");

        jLabel3.setText("Job Title:");

        javax.swing.GroupLayout empViewLayout = new javax.swing.GroupLayout(empView);
        empView.setLayout(empViewLayout);
        empViewLayout.setHorizontalGroup(
            empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empViewLayout.createSequentialGroup()
                .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empViewLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empFieldCreateZIP)
                            .addComponent(empFieldCreateAddress)
                            .addComponent(empFieldCreateEmail)
                            .addComponent(empFieldCreatePhoneNo)
                            .addComponent(empFieldCreateLName)
                            .addComponent(empFieldCreateFName)
                            .addComponent(empCBoxLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empCBOXTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(empViewLayout.createSequentialGroup()
                                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(22, 22, 22)
                                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(empFieldDate)
                                            .addComponent(empFieldEmpID)
                                            .addComponent(empFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(empViewLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(22, 22, 22)
                                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(empFieldEmpIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(empButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(empButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(empButtonCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        empViewLayout.setVerticalGroup(
            empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empViewLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empViewLayout.createSequentialGroup()
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(empFieldCreateFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empFieldCreateLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empFieldCreatePhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(empFieldCreateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empFieldCreateAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empFieldCreateZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empCBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empCBOXTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empButtonCreate)
                        .addGap(106, 106, 106)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empFieldEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(empFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(empFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empButtonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(empViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(empFieldEmpIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empButtonDelete)
                        .addGap(64, 64, 64))
                    .addGroup(empViewLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(empView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(empView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empFieldEmpIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldEmpIDFocusGained
        // TODO add your handling code here:
        if (empFieldEmpID.getText().equals("Employee ID")) {
            empFieldEmpID.setText("");
        }
    }//GEN-LAST:event_empFieldEmpIDFocusGained

    private void empFieldEmpIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldEmpIDFocusLost
        // TODO add your handling code here:
        if (empFieldEmpID.getText().equals("")) {
            empFieldEmpID.setText("Employee ID");
        }
    }//GEN-LAST:event_empFieldEmpIDFocusLost

    private void empFieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldNameFocusGained
        // TODO add your handling code here:
        if (empFieldName.getText().equals("Name")) {
            empFieldName.setText("");
        }
    }//GEN-LAST:event_empFieldNameFocusGained

    private void empFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldNameFocusLost
        if (empFieldName.getText().equals("")) {
            empFieldName.setText("Name");
        }
    }//GEN-LAST:event_empFieldNameFocusLost

    private void empButtonSearchjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empButtonSearchjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empButtonSearchjButton1ActionPerformed

    private void empFieldEmpIDDeleteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldEmpIDDeleteFocusGained
        if (empFieldEmpIDDelete.getText().equals("Employee ID")) {
            empFieldEmpIDDelete.setText("");
        }
    }//GEN-LAST:event_empFieldEmpIDDeleteFocusGained

    private void empFieldEmpIDDeleteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldEmpIDDeleteFocusLost
        if (empFieldEmpIDDelete.getText().equals("")) {
            empFieldEmpIDDelete.setText("Employee ID");
        }
    }//GEN-LAST:event_empFieldEmpIDDeleteFocusLost

    private void empFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldDateFocusGained
        // TODO add your handling code here:
        if (empFieldDate.getText().equals("yyyy-mm-dd")){
            empFieldDate.setText("");
        }
    }//GEN-LAST:event_empFieldDateFocusGained

    private void empFieldDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldDateFocusLost
        // TODO add your handling code here:
        if (empFieldDate.getText().equals("")){
            empFieldDate.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_empFieldDateFocusLost

    private void empButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empButtonDeleteActionPerformed

    private void empFieldCreateAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateAddressFocusGained
        // TODO add your handling code here:
        if (empFieldCreateAddress.getText().equals("Address")) {
            empFieldCreateAddress.setText("");
        }
    }//GEN-LAST:event_empFieldCreateAddressFocusGained

    private void empFieldCreateAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateAddressFocusLost
        // TODO add your handling code here:
        if (empFieldCreateAddress.getText().equals("")) {
            empFieldCreateAddress.setText("Address");
        }
    }//GEN-LAST:event_empFieldCreateAddressFocusLost

    private void empFieldCreateEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateEmailFocusGained
        // TODO add your handling code here:
        if (empFieldCreateEmail.getText().equals("Email")) {
            empFieldCreateEmail.setText("");
        }
    }//GEN-LAST:event_empFieldCreateEmailFocusGained

    private void empFieldCreateEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateEmailFocusLost
        // TODO add your handling code here:
        if (empFieldCreateEmail.getText().equals("")) {
            empFieldCreateEmail.setText("Email");
        }
    }//GEN-LAST:event_empFieldCreateEmailFocusLost

    private void empFieldCreatePhoneNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreatePhoneNoFocusGained
        // TODO add your handling code here:
        if (empFieldCreatePhoneNo.getText().equals("Phone No")) {
            empFieldCreatePhoneNo.setText("");
        }
    }//GEN-LAST:event_empFieldCreatePhoneNoFocusGained

    private void empFieldCreatePhoneNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreatePhoneNoFocusLost
        // TODO add your handling code here:
        if (empFieldCreatePhoneNo.getText().equals("")) {
            empFieldCreatePhoneNo.setText("Phone No");
        }
    }//GEN-LAST:event_empFieldCreatePhoneNoFocusLost

    private void empFieldCreatePhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empFieldCreatePhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empFieldCreatePhoneNoActionPerformed

    private void empFieldCreateLNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateLNameFocusGained
        // TODO add your handling code here:
        if (empFieldCreateLName.getText().equals("Last Name")) {
            empFieldCreateLName.setText("");
        }
    }//GEN-LAST:event_empFieldCreateLNameFocusGained

    private void empFieldCreateLNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateLNameFocusLost
        // TODO add your handling code here:
        if (empFieldCreateLName.getText().equals("")) {
            empFieldCreateLName.setText("Last Name");
        }
    }//GEN-LAST:event_empFieldCreateLNameFocusLost

    private void empFieldCreateFNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateFNameFocusGained
        // TODO add your handling code here:
        if (empFieldCreateFName.getText().equals("First Name")) {
            empFieldCreateFName.setText("");
        }
    }//GEN-LAST:event_empFieldCreateFNameFocusGained

    private void empFieldCreateFNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateFNameFocusLost
        // TODO add your handling code here:
        if (empFieldCreateFName.getText().equals("")) {
            empFieldCreateFName.setText("First Name");
        }
    }//GEN-LAST:event_empFieldCreateFNameFocusLost

    private void empFieldCreateZIPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateZIPFocusGained
        // TODO add your handling code here:
        if (empFieldCreateZIP.getText().equals("ZIP")) {
            empFieldCreateZIP.setText("");
        }
    }//GEN-LAST:event_empFieldCreateZIPFocusGained

    private void empFieldCreateZIPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFieldCreateZIPFocusLost
        // TODO add your handling code here:
        if (empFieldCreateZIP.getText().equals("")) {
            empFieldCreateZIP.setText("ZIP");
        }
    }//GEN-LAST:event_empFieldCreateZIPFocusLost

    private void empButtonCreateActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_empButtonCreateActionPerformed
        String empFName = empFieldCreateFName.getText();
        String empLName = empFieldCreateLName.getText();
        String empPhoneno = empFieldCreatePhoneNo.getText();
        String empEmail = empFieldCreateEmail.getText();
        String empAddress = empFieldCreateAddress.getText();
        int empZIP = Integer.parseInt(empFieldCreateZIP.getText());
        String empTitle = empCBOXTitle.getSelectedItem().toString();
        String empLevel = empCBoxLevel.getSelectedItem().toString();

        con.staffCreate(empFName,empLName,empPhoneno,empEmail,empAddress,empZIP,empTitle);
        con.accountCreate(empFName,empLName,empLevel);
    }//GEN-LAST:event_empButtonCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empButtonCreate;
    private javax.swing.JButton empButtonDelete;
    private javax.swing.JButton empButtonSearch;
    private javax.swing.JComboBox<String> empCBOXTitle;
    private javax.swing.JComboBox<String> empCBoxLevel;
    private javax.swing.JTextField empFieldCreateAddress;
    private javax.swing.JTextField empFieldCreateEmail;
    private javax.swing.JTextField empFieldCreateFName;
    private javax.swing.JTextField empFieldCreateLName;
    private javax.swing.JTextField empFieldCreatePhoneNo;
    private javax.swing.JTextField empFieldCreateZIP;
    private javax.swing.JTextField empFieldDate;
    private javax.swing.JTextField empFieldEmpID;
    private javax.swing.JTextField empFieldEmpIDDelete;
    private javax.swing.JTextField empFieldName;
    private javax.swing.JTable empTable;
    private javax.swing.JPanel empView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
