/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Frames;

import Application.Controller;

/**
 *
 * @author LPNielsen
 */
public class JobsFrame extends javax.swing.JInternalFrame {
    Controller con;

    /**
     * Creates new form Jobs
     */
    public JobsFrame(Controller con) {
        this.con = con;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jobView = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jobTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jobTAreaDesc = new javax.swing.JTextArea();
        jobFieldDelete = new javax.swing.JTextField();
        jobFieldName = new javax.swing.JTextField();
        jobButtonDelete = new javax.swing.JButton();
        jobButtonCreate = new javax.swing.JButton();

        setClosable(true);
        setTitle("Jobs");
        setPreferredSize(new java.awt.Dimension(1200, 779));

        jLabel25.setText("Job Title:");

        jLabel1.setText("Description:");

        jLabel27.setText("Job Name: ");

        jobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Job Title", "Description"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jobTable.setColumnSelectionAllowed(true);
        jobTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jobTable);
        jobTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jobTable.getColumnModel().getColumnCount() > 0) {
            jobTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            jobTable.getColumnModel().getColumn(1).setPreferredWidth(600);
        }

        jobTAreaDesc.setColumns(20);
        jobTAreaDesc.setRows(5);
        jScrollPane1.setViewportView(jobTAreaDesc);

        jobFieldDelete.setText("Job Title");
        jobFieldDelete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jobFieldDeleteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jobFieldDeleteFocusLost(evt);
            }
        });

        jobFieldName.setText("Name");
        jobFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jobFieldNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jobFieldNameFocusLost(evt);
            }
        });

        jobButtonDelete.setText("Delete");
        jobButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobButtonDeleteActionPerformed(evt);
            }
        });

        jobButtonCreate.setText("Create");
        jobButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobButtonCreatejActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jobViewLayout = new javax.swing.GroupLayout(jobView);
        jobView.setLayout(jobViewLayout);
        jobViewLayout.setHorizontalGroup(
            jobViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jobViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jobViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addGroup(jobViewLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(39, 39, 39)
                        .addGroup(jobViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jobFieldDelete)
                            .addComponent(jobButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jobButtonCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jobViewLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jobViewLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jobFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jobViewLayout.setVerticalGroup(
            jobViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobViewLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jobViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jobViewLayout.createSequentialGroup()
                        .addGroup(jobViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jobFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jobButtonCreate)
                        .addGap(149, 149, 149)
                        .addGroup(jobViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jobFieldDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jobButtonDelete))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jobView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jobView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jobFieldDeleteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jobFieldDeleteFocusGained
        if (jobFieldDelete.getText().equals("Job Title")) {
            jobFieldDelete.setText("");
        }
    }//GEN-LAST:event_jobFieldDeleteFocusGained

    private void jobFieldDeleteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jobFieldDeleteFocusLost
        if (jobFieldDelete.getText().equals("")) {
            jobFieldDelete.setText("Job Title");
        }
    }//GEN-LAST:event_jobFieldDeleteFocusLost

    private void jobButtonCreatejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobButtonCreatejActionPerformed
        // TODO add your handling code here:
        con.createJob(jobFieldName.getText(),jobTAreaDesc.getText());
    }                                                                                                                // Variables declaration - do not modify//GEN-LAST:event_jobButtonCreatejActionPerformed

    private void jobFieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jobFieldNameFocusGained
        // TODO add your handling code here:
        if (jobFieldName.getText().equals("Name")) {
            jobFieldName.setText("");
        }
    }//GEN-LAST:event_jobFieldNameFocusGained

    private void jobFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jobFieldNameFocusLost
        // TODO add your handling code here:
        if (jobFieldName.getText().equals("")) {
            jobFieldName.setText("Name");
        }
    }//GEN-LAST:event_jobFieldNameFocusLost

    private void jobButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobButtonDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jobButtonCreate;
    private javax.swing.JButton jobButtonDelete;
    private javax.swing.JTextField jobFieldDelete;
    private javax.swing.JTextField jobFieldName;
    private javax.swing.JTextArea jobTAreaDesc;
    private javax.swing.JTable jobTable;
    private javax.swing.JPanel jobView;
    // End of variables declaration//GEN-END:variables
}
